import { LRParser } from "@lezer/lr";
import { parser as rawParser } from "./huml-parser";

/**
 * The raw Lezer parser for HUML.
 *
 * This is the underlying LR parser generated by Lezer. It can be used
 * to parse HUML code into a syntax tree without the full CodeMirror
 * language support.
 */
export const parser: LRParser = rawParser;
